# Generated by Django 3.1.7 on 2021-04-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bith_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='about_yourself',
            field=models.TextField(blank=True, max_length=2900, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=models.URLField(blank=True, max_length=299, null=True, verbose_name='Профиль на GitHub'),
        ),
    ]
