# Generated by Django 3.1.7 on 2021-03-18 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210315_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Заголовок'),
        ),
    ]
