# Generated by Django 3.1.7 on 2021-03-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_task_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelTable(
            name='project',
            table='Projects',
        ),
    ]
