# Generated by Django 3.1.7 on 2021-04-15 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_project_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('have_user', 'есть пользователь')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
